//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.VotingMethods.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.VotingMethods.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddTableHS {
            get {
                object obj = ResourceManager.GetObject("AddTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Alternative_voices_method_en_US {
            get {
                return ResourceManager.GetString("Alternative_voices_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bord_method_en_US {
            get {
                return ResourceManager.GetString("Bord_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BreakpointHS {
            get {
                object obj = ResourceManager.GetObject("BreakpointHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибраний елемент буфера не є вектором очок. Завантаження неможливе.
        /// </summary>
        internal static string bufferLoadPointsException {
            get {
                return ResourceManager.GetString("bufferLoadPointsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибраний елемент буфера не є профілем. Завантаження неможливе.
        /// </summary>
        internal static string bufferLoadProfileException {
            get {
                return ResourceManager.GetString("bufferLoadProfileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидат #.
        /// </summary>
        internal static string candidateCaption {
            get {
                return ResourceManager.GetString("candidateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommentHS {
            get {
                object obj = ResourceManager.GetObject("CommentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Condorse_method_en_US {
            get {
                return ResourceManager.GetString("Condorse_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Consecutive_exception_method_en_US {
            get {
                return ResourceManager.GetString("Consecutive_exception_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Copland_method_en_US {
            get {
                return ResourceManager.GetString("Copland_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додавання кандидата.
        /// </summary>
        internal static string frmAddCandidateCaption {
            get {
                return ResourceManager.GetString("frmAddCandidateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидат з таким ім&apos;ям вже зареєстрований.
        /// </summary>
        internal static string frmAddCandidateException {
            get {
                return ResourceManager.GetString("frmAddCandidateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейменування кандидатів.
        /// </summary>
        internal static string frmChangeCandidateCaption {
            get {
                return ResourceManager.GetString("frmChangeCandidateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення кандидатів.
        /// </summary>
        internal static string frmDeleteCandidateCaption {
            get {
                return ResourceManager.GetString("frmDeleteCandidateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете видалити обраних кандидатів?.
        /// </summary>
        internal static string frmDeleteCandidateQuestion {
            get {
                return ResourceManager.GetString("frmDeleteCandidateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string frmDeleteCandidateStatusDelete {
            get {
                return ResourceManager.GetString("frmDeleteCandidateStatusDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методи голосування.
        /// </summary>
        internal static string frmModuleCaption {
            get {
                return ResourceManager.GetString("frmModuleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphhs {
            get {
                object obj = ResourceManager.GetObject("graphhs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод абсолютної більшості.
        /// </summary>
        internal static string MethodAbsoluteMajority {
            get {
                return ResourceManager.GetString("MethodAbsoluteMajority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод альтернативних голосів.
        /// </summary>
        internal static string MethodAlternativeVoices {
            get {
                return ResourceManager.GetString("MethodAlternativeVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Борда.
        /// </summary>
        internal static string MethodBord {
            get {
                return ResourceManager.GetString("MethodBord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Кондорсе.
        /// </summary>
        internal static string MethodCondorse {
            get {
                return ResourceManager.GetString("MethodCondorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний профіль не має переможця за Кондорсе.
        /// </summary>
        internal static string methodCondorseException {
            get {
                return ResourceManager.GetString("methodCondorseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод послідовного виключення.
        /// </summary>
        internal static string MethodConsecutiveException {
            get {
                return ResourceManager.GetString("MethodConsecutiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У даному профілі не можна однозначно визначити переможця при порівнянні 2х кандидатів.
        /// </summary>
        internal static string methodConsecutiveExceptionException {
            get {
                return ResourceManager.GetString("methodConsecutiveExceptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Копленда.
        /// </summary>
        internal static string MethodCopland {
            get {
                return ResourceManager.GetString("MethodCopland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний профіль не має переможця за Коплендом.
        /// </summary>
        internal static string methodCopplandException {
            get {
                return ResourceManager.GetString("methodCopplandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час виконання методу &quot;{0}&quot; сталася помилка: &quot;{1}&quot;.
        /// </summary>
        internal static string methodException {
            get {
                return ResourceManager.GetString("methodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_AlternativeVoices {
            get {
                return ResourceManager.GetString("MethodHelp_AlternativeVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f2\fbidi \fmodern\fcharset204\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}
        ///{\f34\fbidi \froman\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_Bord {
            get {
                return ResourceManager.GetString("MethodHelp_Bord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_Condorse {
            get {
                return ResourceManager.GetString("MethodHelp_Condorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_ConsecutiveException {
            get {
                return ResourceManager.GetString("MethodHelp_ConsecutiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_Copland {
            get {
                return ResourceManager.GetString("MethodHelp_Copland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_RelativeMajority {
            get {
                return ResourceManager.GetString("MethodHelp_RelativeMajority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f38\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f42\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_Simpson {
            get {
                return ResourceManager.GetString("MethodHelp_Simpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод відносної більшості.
        /// </summary>
        internal static string MethodRelativeMajority {
            get {
                return ResourceManager.GetString("MethodRelativeMajority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод Сімпсона.
        /// </summary>
        internal static string MethodSimpson {
            get {
                return ResourceManager.GetString("MethodSimpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний профіль не має переможця за Сімпсоном.
        /// </summary>
        internal static string methodSimpsonException {
            get {
                return ResourceManager.GetString("methodSimpsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fmodern\fcharset204\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModuleHelp {
            get {
                return ResourceManager.GetString("ModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewDocumentHS {
            get {
                object obj = ResourceManager.GetObject("NewDocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenSelectedItemHS {
            get {
                object obj = ResourceManager.GetObject("OpenSelectedItemHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap order {
            get {
                object obj = ResourceManager.GetObject("order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrganizerHS {
            get {
                object obj = ResourceManager.GetObject("OrganizerHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap perm {
            get {
                object obj = ResourceManager.GetObject("perm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очки.
        /// </summary>
        internal static string pointsCaption {
            get {
                return ResourceManager.GetString("pointsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно заданий номер кандидата.
        /// </summary>
        internal static string profileOrder1Exception {
            get {
                return ResourceManager.GetString("profileOrder1Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один кандидат не може двічі зустрічатися у порівнянні.
        /// </summary>
        internal static string profileOrder2Exception {
            get {
                return ResourceManager.GetString("profileOrder2Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введені всі очки до профілю або очки задані не в строго спадному порядку.
        /// </summary>
        internal static string profilePointsException {
            get {
                return ResourceManager.GetString("profilePointsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви повинні ввести всі дані до профілю.
        /// </summary>
        internal static string profileProfileFullException {
            get {
                return ResourceManager.GetString("profileProfileFullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один кандидат не може мати 2-х позицій в рейтингу однієї групи виборців.
        /// </summary>
        internal static string profileProfileUniqueException {
            get {
                return ResourceManager.GetString("profileProfileUniqueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість виборців у групі повинна бути додатньою.
        /// </summary>
        internal static string profileVotersCorrectException {
            get {
                return ResourceManager.GetString("profileVotersCorrectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви повинні ввести кількість виборців до кожної з груп виборців.
        /// </summary>
        internal static string profileVotersFullException {
            get {
                return ResourceManager.GetString("profileVotersFullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група виборців #.
        /// </summary>
        internal static string profileVotersGroupCaption {
            get {
                return ResourceManager.GetString("profileVotersGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadialChartHS {
            get {
                object obj = ResourceManager.GetObject("RadialChartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Relative_majority_method_en_US {
            get {
                return ResourceManager.GetString("Relative_majority_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAsWebPageHS {
            get {
                object obj = ResourceManager.GetObject("SaveAsWebPageHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simpson_method_en_US {
            get {
                return ResourceManager.GetString("Simpson_method_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableHS {
            get {
                object obj = ResourceManager.GetObject("TableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при вводі данних в таблицю. Можна вводити тільки числа..
        /// </summary>
        internal static string typeDataGridCellError {
            get {
                return ResourceManager.GetString("typeDataGridCellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Допомога {
            get {
                return ResourceManager.GetString("Допомога", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_альтернативних_голосів_uk_UA {
            get {
                return ResourceManager.GetString("Метод_альтернативних_голосів_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_альтернативных_голосов_ru_RU {
            get {
                return ResourceManager.GetString("Метод_альтернативных_голосов_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\fdbmajor\f31501\fbidi \froman\fcharset204\fprq2{\*\panose 0202060305040502 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Борда_ru_RU {
            get {
                return ResourceManager.GetString("Метод_Борда_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Борда_uk_UA {
            get {
                return ResourceManager.GetString("Метод_Борда_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_відносної_більшості_uk_UA {
            get {
                return ResourceManager.GetString("Метод_відносної_більшості_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Кондорсе_ru_RU {
            get {
                return ResourceManager.GetString("Метод_Кондорсе_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Кондорсе_uk_UA {
            get {
                return ResourceManager.GetString("Метод_Кондорсе_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Копленда_ru_RU {
            get {
                return ResourceManager.GetString("Метод_Копленда_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Копленда_uk_UA {
            get {
                return ResourceManager.GetString("Метод_Копленда_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_относительного_большинства_ru_RU {
            get {
                return ResourceManager.GetString("Метод_относительного_большинства_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_последовательного_исключения_ru_RU {
            get {
                return ResourceManager.GetString("Метод_последовательного_исключения_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_послідовного_виключення_uk_UA {
            get {
                return ResourceManager.GetString("Метод_послідовного_виключення_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Симпсона_ru_RU {
            get {
                return ResourceManager.GetString("Метод_Симпсона_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1058\deflangfe1058{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f38\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f42\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Сімпсона_uk_UA {
            get {
                return ResourceManager.GetString("Метод_Сімпсона_uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}
        ///{\f37\froman\fcharset238\fprq2 Times New Roman CE;}{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\froman\fcharset177\fprq2 Times New Roman (Hebrew);}
        ///{\f43\froman\fcharset178\fprq2 Times New Roman (Arabic);}{\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Метод_Сімпсона_uk_UA1 {
            get {
                return ResourceManager.GetString("Метод_Сімпсона_uk_UA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Times New Roman Tur;}{\f42\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f43\fbidi \froman\fcharset178\fpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Помощь {
            get {
                return ResourceManager.GetString("Помощь", resourceCulture);
            }
        }
    }
}
