//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.ConflictsAndCompromises.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.ConflictsAndCompromises.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oi - Множина обережних стратегій.
        /// </summary>
        internal static string CarefulStrategyMethodName {
            get {
                return ResourceManager.GetString("CarefulStrategyMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNE - Множина сильних Нешівських рівноваг.
        /// </summary>
        internal static string CHMethodName {
            get {
                return ResourceManager.GetString("CHMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di - Множина домінуючих стратегій.
        /// </summary>
        internal static string DiMethodName {
            get {
                return ResourceManager.GetString("DiMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D - Множина рівноваг у домінуючих стратегіях.
        /// </summary>
        internal static string DMethodName {
            get {
                return ResourceManager.GetString("DMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JR - Множина гарантованих результатів.
        /// </summary>
        internal static string JRMethodName {
            get {
                return ResourceManager.GetString("JRMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_CarefulStrategy {
            get {
                return ResourceManager.GetString("MethodHelp_CarefulStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_D {
            get {
                return ResourceManager.GetString("MethodHelp_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_Di {
            get {
                return ResourceManager.GetString("MethodHelp_Di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_JR {
            get {
                return ResourceManager.GetString("MethodHelp_JR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_NDi {
            get {
                return ResourceManager.GetString("MethodHelp_NDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_NE {
            get {
                return ResourceManager.GetString("MethodHelp_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs24\u1054?\u1087?\u1090?\u1080?\u1084?\u1091?\u1084? \u1079?\u1072? \u1055?\u1072?\u1088?\u1077?\u1090?\u1086?\par
        ///\pard\fi710\sa200\sl276\slmult1\b0\u1054?\u1087?\u1090?\u1080?\u1084?\u1091?\u1084? \u1055?\u1072?\u1088?\u1077?\u1090?\u1086? \emdash  \u1090?\u1072?\u1082?\u1080?\u1081? \u1089?\u1090?\u1072?\u1085? \u1089?\u1080?\u1089?\u1090?\u1077? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_PO {
            get {
                return ResourceManager.GetString("MethodHelp_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f38\froman\fcharset0\fprq2 Times New Roman;}{\f36\froman\fcharset238\fprq2 Times New Roman CE;}{\f39\froman\fcharset161\fprq2 Times New Roman Greek;}
        ///{\f40\froman\fcharset162\fprq2 Times New Roman Tur;}{\f41\froman\fcharset177\fprq2 Times New Roman (H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_WEi {
            get {
                return ResourceManager.GetString("MethodHelp_WEi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f39\froman\fcharset0\fprq2 Times New Roman;}{\f37\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f40\froman\fcharset161\fprq2 Times New Roman Greek;}{\f41\froman\fcharset162\fprq2 Tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModuleHelp {
            get {
                return ResourceManager.GetString("ModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDi - Множина недомінованих стратегій.
        /// </summary>
        internal static string NDiMethodName {
            get {
                return ResourceManager.GetString("NDiMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE - Множина рівноваг за Нешем.
        /// </summary>
        internal static string NEMethodName {
            get {
                return ResourceManager.GetString("NEMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П - Переговорна множина.
        /// </summary>
        internal static string PMethodName {
            get {
                return ResourceManager.GetString("PMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO - Множина Парето-оптимальних рішень.
        /// </summary>
        internal static string POMethodName {
            get {
                return ResourceManager.GetString("POMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SЕі - множина і-рівноваг за Штакельбергом.
        /// </summary>
        internal static string WEiMethodName {
            get {
                return ResourceManager.GetString("WEiMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE - Множина складних рівноваг (Перший - гравець №1).
        /// </summary>
        internal static string XNT1MethodName {
            get {
                return ResourceManager.GetString("XNT1MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE - Множина складних рівноваг (Перший - гравець №2).
        /// </summary>
        internal static string XNT2MethodName {
            get {
                return ResourceManager.GetString("XNT2MethodName", resourceCulture);
            }
        }
    }
}
