//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.ModuleFuzzyLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.ModuleFuzzyLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бінарні операції над нечіткими множинами.
        /// </summary>
        internal static string binOper {
            get {
                return ResourceManager.GetString("binOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Властивості бінарних нечітких відношень.
        /// </summary>
        internal static string BinOperationsPropMethod {
            get {
                return ResourceManager.GetString("BinOperationsPropMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нечіткі відношення переваги.
        /// </summary>
        internal static string FuzzyPreferenceRelationss {
            get {
                return ResourceManager.GetString("FuzzyPreferenceRelationss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відображення нечітких множин.
        /// </summary>
        internal static string FuzzySetsImage {
            get {
                return ResourceManager.GetString("FuzzySetsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f41\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_binOper {
            get {
                return ResourceManager.GetString("MethodHelp_binOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f38\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0604030504040204}Tahom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_BinOperationsPropMethod {
            get {
                return ResourceManager.GetString("MethodHelp_BinOperationsPropMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset204 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset204 Liberation Sans{\*\falt Arial};}{\f5\fnil\fprq0\fcharset204 sans-serif{\*\falt Arial};}{\f6\fnil\fprq0\fcharset204 Linux Libertine{\*\falt Georgia};}{\f7\fnil\fprq0\fcharset204 Verdana{\*\falt Arial};}{\f8\froman\fprq2\fcharset128 Times New Roman;}{\f9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_FuzzyPreferenceRelations {
            get {
                return ResourceManager.GetString("MethodHelp_FuzzyPreferenceRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f37\fbidi \fswiss\fcharset204\fprq2{\*\panose 020f0502020204030204}Calibri;}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_FuzzySetsImageMethod {
            get {
                return ResourceManager.GetString("MethodHelp_FuzzySetsImageMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1058\deflangfe1058\themelang1058\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f34\fbidi \froman\fcharset204\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f38\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0604030504040204}Tahoma;}
        ///{\flomajor\f31500\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodHelp_OperOnRelaionMethods {
            get {
                return ResourceManager.GetString("MethodHelp_OperOnRelaionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операції над нечіткими відношеннями.
        /// </summary>
        internal static string MethodOperationsOnRelationships {
            get {
                return ResourceManager.GetString("MethodOperationsOnRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операції над нечіткими відношеннями.
        /// </summary>
        internal static string OperationOnRelation {
            get {
                return ResourceManager.GetString("OperationOnRelation", resourceCulture);
            }
        }
    }
}
